name: pure_mixpanel
description: A new pure Dart library for Mixpanel analytics.
version: 1.0.9
author: Nicholas Manning <puremixpanel@gmail.com>
homepage: https://github.com/seenickcode/pure_mixpanel

dependencies:
  flutter:
    sdk: flutter
  meta: 1.1.7
  http: 0.12.0+2
  test: any

dev_dependencies:
  flutter_test:
    sdk: flutter

environment:
  sdk: ">=2.0.0 <=3.0.0"
  flutter: ">=1.0.0"